baseurl = "https://omicsdi.github.io/"
languageCode = "en-us"
Title = "OmicsDI Blog"
HasCJKLanguage = true
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "OmicsDI Team"

[Params]
  AuthorHomepage = "http://www.omicsdi.org"
  Author="OmicsDI Team"
  disqusShortname = "omicsdi"
  BottomIntroduce = "Blog Posts and Help Pages for OmicsDI </br> including examples, tutorials, etc."
  Description = ""
  Subtitle    = "Linking new Knowledge in Public Data"
  Twitter     = "omicsdi"
  GitHub      = "omicsdi"
  Gitter      = "https://gitter.im/BD2K-DDI/OmicsDI-Support"
  Home        = "https://omicsdi.github.io/"
  Imglogo     = "img/OmicsDI-icon-3.png"
  AuthorImg   = "img/OmicsDI-icon-3.png"
  DateFormat  = "2006/01/02"
  MonthFormat = "2006/01/"

  #[Params.DuoShuo]
  #  ShortName = "coderzh"

  [Params.Disqus]
    ShortName = "omicsdi"

  [Params.GoogleAnalytics]
    ID = "UA-70417662-3"

  [Params.Strings]
    Search = "Search"
    PageNotFound = "Page Not Found"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "Categories"
    Archive = "Archive"
    Tags = "Tags"
    TagCloud = "WordCloud"
    Rss = "RSS"
    TableOfContents = "Table of Contents"

[Menu]
  [[Menu.Main]]
    Name = "Home"
    URL = "/"
    Weight = 1

  [[Menu.Main]]
    Name = "OmicsDI"
    URL = "http://www.omicsdi.org"
    Weight = 2

  [[Menu.Main]]
    Name = "GitHub"
    URL = "http://github.com/OmicsDI"
    Weight = 2


